# Generated by Django 2.2.5 on 2020-11-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Doing'), (2, 'Done')])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
